image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      yarn
      pm2 start mongod
      pm2 start "MINIO_ACCESS_KEY=hydro MINIO_SECRET_KEY=hydrohydro minio server /home/gitpod/file" --name minio
      pm2 start "/home/gitpod/.cargo/bin/sonic -c /home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/sonic-server-1.3.0/config.cfg" --name sonic
      yarn build:ui
      npx hydrooj cli system set server.port 2333
      npx hydrooj cli user create root@hydro.local root rootroot 2
      npx hydrooj cli user setSuperAdmin 2
      yarn debug
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - vscode-icons-team.vscode-icons
    - samuelcolvin.jinjahtml
    - tabnine.tabnine-vscode
    - gruntfuggly.todo-tree
