nodeLinker: node-modules

npmPublishAccess: public

packageExtensions:
  koa-body@*:
    dependencies:
      "@types/koa": "*"
      koa: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-berry.js
